name: Select, Pull, and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select a Docker image to pull and run'
        required: true
        default: 'ubuntu,centos,alpine,debian,fedora'

jobs:
  select_pull_and_run_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Run Docker Image
        run: docker run -d ${{ github.event.inputs.docker_image }}:latest
