name: Select and Pull Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select a Docker image to pull'
        required: true
        default: 'Select'
        options:
          - 'ubuntu:latest'
          - 'centos:latest'
          - 'alpine:latest'
          - 'debian:latest'
          - 'fedora:latest'

jobs:
  select_and_pull_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull ${{ github.event.inputs.docker_image }}
